### ISSUE TITLE
Adding the detection_idx number to the sampling results pictures

### ISSUE THREAD

**Issue by jason-airst** [timmh/distance-estimation#1]
It would be helpful if the sample results pictures included the detection_indx number for each of the animals in a picture. This is not a major issue when all animals in a picture are the same species, but is necessary to know when there are more then one species in the photo. If this is not possible then it would be useful for there to be an explanation in the package's GitHub about how the detection_indx numbers are generated for animals in the photos. Based on the example photo "T09___HT_cam19_433258_5887473_20190708 ___ 07080012___2019-07-08-09-52-31" it does not seem that order of the detection_indx numbers in the photo of the 3 deer is anything but random.

**Comment by timmh** [comment]
Hey @jason-airst, you are right, there should definitely be a simpler way to associate detections with distance measurements. Right now, the detections are sorted from the center of the image outwards (see [here](https://github.com/timmh/distance-estimation/blob/16240e088414924ea31a946abf998e968bf0b65c/run.py#L197-L200)).

**Comment by jason-airst** [comment]
Thank you. That is what I thought. 

I would also like to say that I that I find your program to be very user friendly.

**Comment by timmh** [comment]
With 6f65c1a and [release v1.3.3](https://github.com/timmh/distance-estimation/releases/tag/v1.3.3) there is now an option to visualize the detection_idx in the visualizations (`draw_detection_ids`).
